/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.jframes;

import javax.swing.ImageIcon;

/**
 *
 * @author Jose
 */
public class JFrame_App extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_App
     */
    public JFrame_App() {
        initComponents();
        this.setIconImage(new ImageIcon("./src/vista/imagenes/favicon.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoFutbolistaAniadir = new javax.swing.JDialog();
        jPanel_FutbolistaAniadir = new vista.jpanels.JPanel_FutbolistaAniadir();
        dialogoFutbolistaModificar = new javax.swing.JDialog();
        jPanel_FutbolistaModificar = new vista.jpanels.JPanel_FutbolistaModificar();
        dialogoClubAniadir = new javax.swing.JDialog();
        jPanel_ClubAniadir = new vista.jpanels.JPanel_ClubAniadir();
        dialogoClubModificar = new javax.swing.JDialog();
        jPanel_ClubModificar = new vista.jpanels.JPanel_ClubModificar();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane_Cabecera = new javax.swing.JTabbedPane();
        jPanel_futbolistas = new vista.jpanels.JPanel_Tablas();
        jPanel_clubs = new vista.jpanels.JPanel_Tablas();

        javax.swing.GroupLayout dialogoFutbolistaAniadirLayout = new javax.swing.GroupLayout(dialogoFutbolistaAniadir.getContentPane());
        dialogoFutbolistaAniadir.getContentPane().setLayout(dialogoFutbolistaAniadirLayout);
        dialogoFutbolistaAniadirLayout.setHorizontalGroup(
            dialogoFutbolistaAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_FutbolistaAniadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogoFutbolistaAniadirLayout.setVerticalGroup(
            dialogoFutbolistaAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_FutbolistaAniadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dialogoFutbolistaModificarLayout = new javax.swing.GroupLayout(dialogoFutbolistaModificar.getContentPane());
        dialogoFutbolistaModificar.getContentPane().setLayout(dialogoFutbolistaModificarLayout);
        dialogoFutbolistaModificarLayout.setHorizontalGroup(
            dialogoFutbolistaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_FutbolistaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoFutbolistaModificarLayout.setVerticalGroup(
            dialogoFutbolistaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoFutbolistaModificarLayout.createSequentialGroup()
                .addComponent(jPanel_FutbolistaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogoClubAniadirLayout = new javax.swing.GroupLayout(dialogoClubAniadir.getContentPane());
        dialogoClubAniadir.getContentPane().setLayout(dialogoClubAniadirLayout);
        dialogoClubAniadirLayout.setHorizontalGroup(
            dialogoClubAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoClubAniadirLayout.setVerticalGroup(
            dialogoClubAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout dialogoClubModificarLayout = new javax.swing.GroupLayout(dialogoClubModificar.getContentPane());
        dialogoClubModificar.getContentPane().setLayout(dialogoClubModificarLayout);
        dialogoClubModificarLayout.setHorizontalGroup(
            dialogoClubModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoClubModificarLayout.setVerticalGroup(
            dialogoClubModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane_Cabecera.addTab("Futbolistas", jPanel_futbolistas);
        jTabbedPane_Cabecera.addTab("Clubs", jPanel_clubs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Cabecera)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane_Cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog dialogoClubAniadir;
    public javax.swing.JDialog dialogoClubModificar;
    public javax.swing.JDialog dialogoFutbolistaAniadir;
    public javax.swing.JDialog dialogoFutbolistaModificar;
    private javax.swing.JPanel jPanel1;
    public vista.jpanels.JPanel_ClubAniadir jPanel_ClubAniadir;
    public vista.jpanels.JPanel_ClubModificar jPanel_ClubModificar;
    public vista.jpanels.JPanel_FutbolistaAniadir jPanel_FutbolistaAniadir;
    public vista.jpanels.JPanel_FutbolistaModificar jPanel_FutbolistaModificar;
    public vista.jpanels.JPanel_Tablas jPanel_clubs;
    public vista.jpanels.JPanel_Tablas jPanel_futbolistas;
    public javax.swing.JTabbedPane jTabbedPane_Cabecera;
    // End of variables declaration//GEN-END:variables
}
