/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.jframes;

import javax.swing.ImageIcon;

/**
 *
 * @author Jose
 */
public class JFrame_App extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_App
     */
    public JFrame_App() {
        initComponents();
        this.setIconImage(new ImageIcon("./src/vista/imagenes/favicon.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoFutbolistaAniadir = new javax.swing.JDialog();
        jPanel_FutbolistaAniadir = new vista.jpanels.JPanel_FutbolistaAniadir();
        dialogoFutbolistaModificar = new javax.swing.JDialog();
        jPanel_FutbolistaModificar = new vista.jpanels.JPanel_FutbolistaModificar();
        dialogoClubAniadir = new javax.swing.JDialog();
        jPanel_ClubAniadir = new vista.jpanels.JPanel_ClubAniadir();
        dialogoClubModificar = new javax.swing.JDialog();
        jPanel_ClubModificar = new vista.jpanels.JPanel_ClubModificar();
        dialogoAsociar = new javax.swing.JDialog();
        jPanel_Asociar = new vista.jpanels.JPanel_Asociar();
        dialogoBuscar = new javax.swing.JDialog();
        jPanel_Buscar = new vista.jpanels.JPanel_Buscar();
        dialogoCrearCuenta = new javax.swing.JDialog();
        jPanel_CrearCuentaAdmin = new vista.jpanels.JPanel_CrearCuentaAdmin();
        dialogoCambiarContrasenia = new javax.swing.JDialog();
        jPanel_ModificarContrasenia = new vista.jpanels.JPanel_ModificarContrasenia();
        jPanel1 = new javax.swing.JPanel();
        Cuentas = new javax.swing.JTabbedPane();
        jPanel_futbolistas = new vista.jpanels.JPanel_Tablas();
        jPanel_clubs = new vista.jpanels.JPanel_Tablas();
        jPanel_Cuentas = new javax.swing.JPanel();
        btn_cambiarContrasenia = new javax.swing.JButton();
        btn_CrearNuevaCuenta = new javax.swing.JButton();

        javax.swing.GroupLayout dialogoFutbolistaAniadirLayout = new javax.swing.GroupLayout(dialogoFutbolistaAniadir.getContentPane());
        dialogoFutbolistaAniadir.getContentPane().setLayout(dialogoFutbolistaAniadirLayout);
        dialogoFutbolistaAniadirLayout.setHorizontalGroup(
            dialogoFutbolistaAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_FutbolistaAniadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogoFutbolistaAniadirLayout.setVerticalGroup(
            dialogoFutbolistaAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_FutbolistaAniadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dialogoFutbolistaModificarLayout = new javax.swing.GroupLayout(dialogoFutbolistaModificar.getContentPane());
        dialogoFutbolistaModificar.getContentPane().setLayout(dialogoFutbolistaModificarLayout);
        dialogoFutbolistaModificarLayout.setHorizontalGroup(
            dialogoFutbolistaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_FutbolistaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoFutbolistaModificarLayout.setVerticalGroup(
            dialogoFutbolistaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoFutbolistaModificarLayout.createSequentialGroup()
                .addComponent(jPanel_FutbolistaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogoClubAniadirLayout = new javax.swing.GroupLayout(dialogoClubAniadir.getContentPane());
        dialogoClubAniadir.getContentPane().setLayout(dialogoClubAniadirLayout);
        dialogoClubAniadirLayout.setHorizontalGroup(
            dialogoClubAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoClubAniadirLayout.setVerticalGroup(
            dialogoClubAniadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout dialogoClubModificarLayout = new javax.swing.GroupLayout(dialogoClubModificar.getContentPane());
        dialogoClubModificar.getContentPane().setLayout(dialogoClubModificarLayout);
        dialogoClubModificarLayout.setHorizontalGroup(
            dialogoClubModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoClubModificarLayout.setVerticalGroup(
            dialogoClubModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ClubModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout dialogoAsociarLayout = new javax.swing.GroupLayout(dialogoAsociar.getContentPane());
        dialogoAsociar.getContentPane().setLayout(dialogoAsociarLayout);
        dialogoAsociarLayout.setHorizontalGroup(
            dialogoAsociarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Asociar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoAsociarLayout.setVerticalGroup(
            dialogoAsociarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Asociar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout dialogoBuscarLayout = new javax.swing.GroupLayout(dialogoBuscar.getContentPane());
        dialogoBuscar.getContentPane().setLayout(dialogoBuscarLayout);
        dialogoBuscarLayout.setHorizontalGroup(
            dialogoBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoBuscarLayout.createSequentialGroup()
                .addComponent(jPanel_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogoBuscarLayout.setVerticalGroup(
            dialogoBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoBuscarLayout.createSequentialGroup()
                .addComponent(jPanel_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogoCrearCuentaLayout = new javax.swing.GroupLayout(dialogoCrearCuenta.getContentPane());
        dialogoCrearCuenta.getContentPane().setLayout(dialogoCrearCuentaLayout);
        dialogoCrearCuentaLayout.setHorizontalGroup(
            dialogoCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoCrearCuentaLayout.createSequentialGroup()
                .addComponent(jPanel_CrearCuentaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogoCrearCuentaLayout.setVerticalGroup(
            dialogoCrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_CrearCuentaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout dialogoCambiarContraseniaLayout = new javax.swing.GroupLayout(dialogoCambiarContrasenia.getContentPane());
        dialogoCambiarContrasenia.getContentPane().setLayout(dialogoCambiarContraseniaLayout);
        dialogoCambiarContraseniaLayout.setHorizontalGroup(
            dialogoCambiarContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_ModificarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogoCambiarContraseniaLayout.setVerticalGroup(
            dialogoCambiarContraseniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoCambiarContraseniaLayout.createSequentialGroup()
                .addComponent(jPanel_ModificarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Cuentas.addTab("Futbolistas", jPanel_futbolistas);
        Cuentas.addTab("Clubs", jPanel_clubs);

        btn_cambiarContrasenia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_cambiarContrasenia.setText("Cambiar Contraseña");

        btn_CrearNuevaCuenta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_CrearNuevaCuenta.setText("Crear una nueva cuenta");

        javax.swing.GroupLayout jPanel_CuentasLayout = new javax.swing.GroupLayout(jPanel_Cuentas);
        jPanel_Cuentas.setLayout(jPanel_CuentasLayout);
        jPanel_CuentasLayout.setHorizontalGroup(
            jPanel_CuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CuentasLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel_CuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_CrearNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cambiarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );
        jPanel_CuentasLayout.setVerticalGroup(
            jPanel_CuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CuentasLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btn_cambiarContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btn_CrearNuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        Cuentas.addTab("Cuentas", jPanel_Cuentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cuentas)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Cuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane Cuentas;
    public javax.swing.JButton btn_CrearNuevaCuenta;
    public javax.swing.JButton btn_cambiarContrasenia;
    public javax.swing.JDialog dialogoAsociar;
    public javax.swing.JDialog dialogoBuscar;
    public javax.swing.JDialog dialogoCambiarContrasenia;
    public javax.swing.JDialog dialogoClubAniadir;
    public javax.swing.JDialog dialogoClubModificar;
    public javax.swing.JDialog dialogoCrearCuenta;
    public javax.swing.JDialog dialogoFutbolistaAniadir;
    public javax.swing.JDialog dialogoFutbolistaModificar;
    private javax.swing.JPanel jPanel1;
    public vista.jpanels.JPanel_Asociar jPanel_Asociar;
    public vista.jpanels.JPanel_Buscar jPanel_Buscar;
    public vista.jpanels.JPanel_ClubAniadir jPanel_ClubAniadir;
    public vista.jpanels.JPanel_ClubModificar jPanel_ClubModificar;
    public vista.jpanels.JPanel_CrearCuentaAdmin jPanel_CrearCuentaAdmin;
    private javax.swing.JPanel jPanel_Cuentas;
    public vista.jpanels.JPanel_FutbolistaAniadir jPanel_FutbolistaAniadir;
    public vista.jpanels.JPanel_FutbolistaModificar jPanel_FutbolistaModificar;
    public vista.jpanels.JPanel_ModificarContrasenia jPanel_ModificarContrasenia;
    public vista.jpanels.JPanel_Tablas jPanel_clubs;
    public vista.jpanels.JPanel_Tablas jPanel_futbolistas;
    // End of variables declaration//GEN-END:variables
}
